Repository boostcampwm2023/iOS02-moti, pull requests merged in 2023-11, with the labels that each got.

#4 moti 백엔드 프로젝트 생성
  BE/.eslintrc.js
  BE/.gitignore
  BE/.gitkeep
  BE/.prettierrc
  BE/README.md
  BE/nest-cli.json
  BE/package-lock.json
  BE/package.json
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/config/config/index.ts
  BE/src/config/typeorm/index.ts
  BE/src/main.ts
  BE/test/app.e2e-spec.ts
  BE/test/jest-e2e.json
  BE/tsconfig.build.json
  BE/tsconfig.json
Labels: BE, feature

#6 swagger를 설정한다.
  BE/package-lock.json
  BE/package.json
  BE/src/config/swagger/index.ts
  BE/src/main.ts
Labels: BE, feature, 메인

#13 [BE] feat: 커스텀 예외를 추가하고 예외 필터를 적용한다.
  BE/src/common/exception/motimate.excpetion.ts
  BE/src/common/filter/exception.filter.ts
  BE/src/common/filter/unexpected-exception.filter.ts
  BE/src/main.ts
Labels: BE, feature

#14 [iOS] feat: moti 프로젝트를 생성한다
  iOS/.gitignore
  iOS/moti/.swiftlint.yml
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Application/AppDelegate.swift
  iOS/moti/moti/Application/Base.lproj/LaunchScreen.storyboard
  iOS/moti/moti/Application/SceneDelegate.swift
  iOS/moti/moti/Data/.gitignore
  iOS/moti/moti/Data/Package.swift
  iOS/moti/moti/Data/Sources/Data/Data.swift
  iOS/moti/moti/Data/Tests/DataTests/DataTests.swift
  iOS/moti/moti/Domain/.gitignore
  iOS/moti/moti/Domain/Package.swift
  iOS/moti/moti/Domain/Sources/Domain/Domain.swift
  iOS/moti/moti/Domain/Tests/DomainTests/DomainTests.swift
  iOS/moti/moti/Presentation/.gitignore
  iOS/moti/moti/Presentation/Package.swift
  iOS/moti/moti/Presentation/Sources/Presentation/ViewController.swift
  iOS/moti/moti/Presentation/Tests/PresentationTests/PresentationTests.swift
  iOS/moti/moti/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/moti/moti/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/moti/moti/Resource/Assets.xcassets/Contents.json
  iOS/moti/moti/Resource/Info.plist
  iOS/moti/moti/moti.entitlements
Labels: feature, iOS, 메인

#16 [iOS] feat: 커밋에 따른 빌드 번호 증가
  iOS/moti/moti.xcodeproj/project.pbxproj
Labels: feature, iOS, 메인

#26 스플래시 화면 UI를 구현한다.
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Application/SceneDelegate.swift
  iOS/moti/moti/Presentation/Package.swift
  iOS/moti/moti/Presentation/Sources/Common/BaseViewController.swift
  iOS/moti/moti/Presentation/Sources/Launch/LaunchView.swift
  iOS/moti/moti/Presentation/Sources/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Tests/PresentationTests/PresentationTests.swift
  iOS/moti/moti/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/moti/moti/Resource/Assets.xcassets/AppIcon.appiconset/앱 아이콘.png
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoBlue.imageset/Contents.json
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoBlue.imageset/moti-icon-blue 1.png
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoBlue.imageset/moti-icon-blue 2.png
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoBlue.imageset/moti-icon-blue.png
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoWhite.imageset/Contents.json
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoWhite.imageset/moti-icon-white 1.png
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoWhite.imageset/moti-icon-white 2.png
  iOS/moti/moti/Resource/Assets.xcassets/MotiLogoWhite.imageset/moti-icon-white.png
Labels: feature, iOS, 메인

#19 git action CI를 적용한다.
  .github/workflows/be.ci.yml
  BE/package.json
Labels: enhancement, BE

#23 typeorm 설정을 커스텀한다.
  BE/src/config/typeorm/camel-snake-name-strategy.spec.ts
  BE/src/config/typeorm/camel-snake-name-strategy.ts
  BE/src/config/typeorm/custom-repository.decorator.ts
  BE/src/config/typeorm/custom-typeorm.module.ts
  BE/src/config/typeorm/index.ts
Labels: enhancement, BE, 메인

#29 유저엔티티 생성
  BE/src/common/entities/base.entity.ts
  BE/src/users/entities/role.entity.ts
  BE/src/users/entities/users-role.entity.ts
  BE/src/users/entities/users.entity.ts
Labels: BE, feature, 메인

#31 [Enhancement] Swift Package의 내부 구조를 개선한다.
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Application/SceneDelegate.swift
  iOS/moti/moti/Data/Package.swift
  iOS/moti/moti/Domain/Package.swift
  iOS/moti/moti/Presentation/Package.swift
  iOS/moti/moti/Presentation/Sources/Common/BaseViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/AutoLayout/AutoLayoutWrapper+UIView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/AutoLayout/AutoLayoutWrapper.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/BaseViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchCoodinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  iOS/moti/moti/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/moti/moti/Resource/Assets.xcassets/AppIcon.appiconset/앱 아이콘.png
Labels: enhancement, iOS

#28 Exception Handler 수정
  BE/src/common/exception/motimate.excpetion.ts
  BE/src/common/filter/exception.filter.ts
  BE/src/common/filter/unexpected-exception.filter.ts
  BE/src/main.ts
Labels: enhancement, BE, bug

#33 CI 테스트 환경 구축
  .github/workflows/be.ci.yml
  BE/package-lock.json
  BE/package.json
  BE/src/config/typeorm/index.ts
Labels: enhancement, BE, 메인

#35 [Enhancement] 요청 검증기 적용하기
  BE/package-lock.json
  BE/package.json
  BE/src/main.ts
Labels: enhancement, BE, 서포트

#41 요청 검증기 응답 wrapper 적용
  BE/src/common/exception/motimate.excpetion.ts
  BE/src/config/validation/index.ts
  BE/src/main.ts
Labels: enhancement, BE, 서포트

#43 sqlite를 고려한 엔티티 코드 변경
  BE/src/users/entities/users.entity.ts
Labels: enhancement, BE, bug

#39 로그인 화면 UI를 구현한다
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/moti-icon-blue 1.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/moti-icon-blue 2.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/moti-icon-blue.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoWhite.imageset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoWhite.imageset/moti-icon-white 1.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoWhite.imageset/moti-icon-white 2.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoWhite.imageset/moti-icon-white.png
  iOS/moti/moti/Design/Sources/Design/MotiImage.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Authorization/AuthButtonFactory.swift
  iOS/moti/moti/Presentation/Sources/Presentation/AutoLayout/AutoLayoutWrapper+UIView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginViewController.swift
Labels: feature, iOS, 메인

#44 애플 로그인을 버튼을 누르면 애플 로그인을 요청한다.
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Presentation/Package.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Authorization/AppleLoginRequester.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Authorization/LoginRequester.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginViewController.swift
Labels: feature, iOS, 메인

#45 애플 로그인을 버튼을 누르면 애플 로그인을 요청한다
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Presentation/Sources/Presentation/Authorization/AppleLoginRequester.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginViewController.swift
Labels: enhancement, iOS, 메인

#48 CI 스크립트 변경
  .github/workflows/be.ci.yml
Labels: BE, 서포트, bug

#50 배경색 다크모드를 지원한다, 버전 조회 API를 테스트한다.
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Color/MotiBackground.colorset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/moti-icon-white 1.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/moti-icon-white 2.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/MotiLogoBlue.imageset/moti-icon-white.png
  iOS/moti/moti/Design/Sources/Design/UIColor+MotiColor.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/BaseViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginView.swift
  iOS/moti/moti/Presentation/Tests/PresentationTests/PresentationTests.swift
  iOS/moti/moti/Presentation/Tests/PresentationTests/UseCase/FetchVersionUseCaseTests.swift
  iOS/moti/moti/Presentation/Tests/PresentationTests/ViewModel/LaunchViewModelTests.swift
Labels: feature, iOS, 서포트

#40 Apple OAuth2 로그인을 구현한다.
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/auth/application/identity-token.spec.ts
  BE/src/auth/application/identity-token.ts
  BE/src/auth/application/jwt-utils.spec.ts
  BE/src/auth/application/jwt-utils.ts
  BE/src/auth/application/oauth-handler.spec.ts
  BE/src/auth/application/oauth-handler.ts
  BE/src/auth/application/oauth-requester.spec.ts
  BE/src/auth/application/oauth-requester.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/exception/expired-token.exception.ts
  BE/src/auth/exception/fetch-public-key.exception.ts
  BE/src/auth/exception/invalid-token.exception.ts
  BE/src/auth/index.ts
  BE/src/common/exception/error-code.ts
  BE/src/common/exception/motimate.excpetion.ts
  BE/src/config/config/index.ts
Labels: BE, feature, 메인

#56 트랜잭션 매니저 개발
  BE/src/app.module.ts
  BE/src/config/transaction-manager/index.ts
  BE/src/config/transaction-manager/transaction-manager.ts
  BE/src/config/transaction-manager/transaction.module.ts
Labels: BE, 서포트, bug

#57 버전 조회 API 를 요청한다
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Data/Package.swift
  iOS/moti/moti/Data/Sources/Data/Data.swift
  iOS/moti/moti/Data/Sources/Data/Network/Common/NetworkError.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/ResponseDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/VersionDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/Endpoint.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/Requestable.swift
  iOS/moti/moti/Data/Sources/Data/Network/Extension/Encodable.swift
  iOS/moti/moti/Data/Sources/Data/Network/Provider/Provider.swift
  iOS/moti/moti/Data/Sources/Repository/MockVersionRepository.swift
  iOS/moti/moti/Data/Sources/Repository/VersionRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/DataTests.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/VersionRepositoryTests.swift
  iOS/moti/moti/Domain/Sources/Domain/Domain.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/Version.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/VersionRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchVersionUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchCoodinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginCoordinator.swift
Labels: feature, iOS, 메인

#59 [Feature] 버전 API 작성하기
  BE/src/app.module.ts
  BE/src/common/exception/error-code.ts
  BE/src/common/filter/exception.filter.ts
  BE/src/operate/application/operate.service.spec.ts
  BE/src/operate/application/operate.service.ts
  BE/src/operate/controller/operate.controller.ts
  BE/src/operate/domain/moti-policy.domain.ts
  BE/src/operate/dto/moti-policy-create.ts
  BE/src/operate/dto/moti-policy-response.ts
  BE/src/operate/entities/moti-policy-repository.spec.ts
  BE/src/operate/entities/moti-policy.entity.ts
  BE/src/operate/entities/moti-policy.repository.ts
  BE/src/operate/exception/policy-already-exists.exception.ts
  BE/src/operate/exception/policy-not-found.exception.ts
  BE/src/operate/operate.module.ts
  BE/test/common/transaction-test.ts
Labels: BE, feature, 메인

#61 사용자에게 유저 코드를 부여한다.
  BE/src/auth/application/user-code-generator.spec.ts
  BE/src/auth/application/user-code-generator.ts
  BE/src/users/domain/user.domain.ts
  BE/src/users/entities/user.entity.ts
  BE/src/users/entities/user.repository.spec.ts
  BE/src/users/entities/user.repository.ts
  BE/src/users/entities/users-role.entity.ts
  BE/src/users/entities/users.entity.ts
Labels: BE, feature, 메인

#63 달성기록 데이터베이스 설계
  BE/src/achievement/entities/achievement.entity.ts
Labels: BE, feature, 메인

#69 Logger를 구현한다
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Core/Sources/Core/Logger.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginViewController.swift
Labels: feature, iOS, 메인

#74 CI를 분리한다.
  .github/workflows/be.ci.yml
Labels: enhancement, BE

#78 NODE_ENV에 따른 typeorm 설정 변경
  BE/src/config/typeorm/index.ts
Labels: enhancement, BE, bug

#65 Api 응답 래퍼 적용하기
  BE/src/common/api/api-data.ts
  BE/src/common/filter/exception.filter.ts
  BE/src/common/filter/unexpected-exception.filter.ts
  BE/src/operate/controller/operate.controller.ts
Labels: enhancement, BE, 서포트

#81 API 스펙 맞추기
  BE/src/config/config/validation-decorator.ts
  BE/src/config/validation/index.ts
  BE/src/config/validation/validation-pipe-options.spec.ts
  BE/src/operate/controller/operate.controller.ts
  BE/src/operate/dto/moti-policy-create.ts
Labels: enhancement, BE, 서포트

#83 Coordinator 구조를 개선한다.
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Application/AppCoordinator.swift
  iOS/moti/moti/Application/SceneDelegate.swift
  iOS/moti/moti/Core/Sources/Core/Coordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchCoodinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: enhancement, iOS, 메인

#85 Joi를 사용해서 환경변수 검증하기
  .github/workflows/be.ci.yml
  BE/package-lock.json
  BE/package.json
  BE/src/config/config/index.ts
  BE/src/config/typeorm/index.ts
Labels: enhancement, BE

#91 버전 수정 Api 작성하기
  BE/src/config/config/validation-decorator.ts
  BE/src/config/transaction-manager/index.ts
  BE/src/config/transaction-manager/transaction-manager.ts
  BE/src/operate/application/operate.service.spec.ts
  BE/src/operate/application/operate.service.ts
  BE/src/operate/controller/operate.controller.ts
  BE/src/operate/domain/moti-policy.domain.ts
  BE/src/operate/dto/index.ts
  BE/src/operate/dto/moti-policy-idempotent-update.ts
  BE/src/operate/dto/moti-policy-partitial-update.ts
Labels: enhancement, BE, 메인

#90 개인 홈 - 달성 기록 리스트를 MockRepository 에서 가져와 보여준다.
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Data/Sources/Data/Network/DTO/RecordListDTO.swift
  iOS/moti/moti/Data/Sources/Repository/MockRecordListRepository.swift
  iOS/moti/moti/Design/Sources/Design/Font.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/Record.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/RecordListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchRecordListUseCase.swift
  iOS/moti/moti/Presentation/Package.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Extension/CollectionReusableView+Extension.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Extension/UICollectionView+Extension.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/RecordListViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/RecordView/HeaderView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/RecordView/RecordCollectionViewCell.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/RecordView/RecordDiffableDataSource.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#96 BaseURL을 XCConfig로 관리한다.
  iOS/moti/.swiftlint.yml
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Resource/Info.plist
Labels: feature, iOS, 메인

#95 JWT 토큰을 통한 인증 방식을 구현한다.
  BE/src/app.module.ts
  BE/src/auth/application/auth.service.spec.ts
  BE/src/auth/application/auth.service.ts
  BE/src/auth/application/jwt-utils.spec.ts
  BE/src/auth/application/jwt-utils.ts
  BE/src/auth/application/oauth-handler.spec.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/controller/auth.controller.ts
  BE/src/auth/decorator/athenticated-user.decorator.ts
  BE/src/auth/dto/apple-login-request.dto.ts
  BE/src/auth/dto/apple-login-response.dto.ts
  BE/src/auth/dto/refresh-auth-request.dto.ts
  BE/src/auth/dto/refresh-auth-response.dto.ts
  BE/src/auth/guard/access-token.guard.ts
  BE/src/auth/index.ts
  BE/src/users/application/users.service.spec.ts
  BE/src/users/application/users.service.ts
  BE/src/users/dto/user.dto.ts
  BE/src/users/entities/user.entity.ts
  BE/src/users/entities/user.repository.spec.ts
  BE/src/users/entities/user.repository.ts
  BE/src/users/users.module.ts
Labels: BE, feature, 메인

#103 테스트 시 DDL 충돌을 해결하기 위해 단일스레드로 테스트를 실행한다.
  BE/package.json
Labels: BE, 서포트, bug

#104 레포지토리 기반 코드 구조 개선
  BE/src/config/transaction-manager/transactional-repository.ts
  BE/src/operate/entities/moti-policy.repository.ts
  BE/src/users/entities/user.repository.spec.ts
  BE/src/users/entities/user.repository.ts
Labels: enhancement, BE

#106 카테고리 리스트 UI를 구현한다.
  iOS/moti/moti/Data/Sources/Data/Network/DTO/AchievementDTO.swift
  iOS/moti/moti/Data/Sources/Repository/MockRecordListRepository.swift
  iOS/moti/moti/Design/Sources/Design/BounceButton.swift
  iOS/moti/moti/Design/Sources/Design/Font.swift
  iOS/moti/moti/Design/Sources/Design/UIView+Extension.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/Achievement.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/AchievementListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/RecordListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchAchievementListUseCase.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchRecordListUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/CompositionalLayoutFactory.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/ListDiffableDataSource.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/AchievementCollectionViewCell.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/CategoryCollectionViewCell.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/HeaderView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/RecordListViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/RecordView/RecordDiffableDataSource.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarViewController.swift
Labels: feature, iOS, 메인

#111 TransactionalRepository 타입 안정성 개선
  BE/src/config/transaction-manager/transactional-repository.ts
Labels: enhancement, BE, 서포트

#112 Login 성공 시 홈 화면으로 이동한다.
  iOS/moti/moti/Application/AppCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginViewController.swift
Labels: feature, iOS, 메인

#108 카테고리 추가 API 작성하기
  BE/src/app.module.ts
  BE/src/auth/auth.module.ts
  BE/src/category/application/category.service.spec.ts
  BE/src/category/application/category.service.ts
  BE/src/category/category.module.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/domain/category.domain.ts
  BE/src/category/dto/category-create.ts
  BE/src/category/dto/category.response.ts
  BE/src/category/entities/category.entity.ts
  BE/src/category/entities/category.repository.spec.ts
  BE/src/category/entities/category.repository.ts
  BE/src/users/users.module.ts
  BE/test/user/users-fixture.ts
  BE/test/user/users-test.module.ts
Labels: BE, feature, 메인

#116 자동 로그인을 호출하고 화면을 이동한다.
  iOS/moti/moti/Application/AppCoordinator.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Repository/LoginRepository.swift
  iOS/moti/moti/Data/Sources/Repository/Mock/MockLoginRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/LoginRepositoryTests.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/NetworkLoginRepositoryTests.swift
  iOS/moti/moti/Domain/Package.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/LoginRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/AutoLoginUseCase.swift
  iOS/moti/moti/Domain/Tests/DomainTests/DomainTests.swift
  iOS/moti/moti/Domain/Tests/UseCaseTests/LoginUseCaseTests.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchCoodinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginViewModel.swift
Labels: feature, iOS, 메인

#115 CategoryResponse 경로 변경
  BE/src/category/controller/category.controller.ts
Labels: BE, bug

#118 홈 화면 내비게이션 UI를 구현한다.
  iOS/moti/moti/Application/SceneDelegate.swift
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/프로필사진 1.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/프로필사진 2.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/프로필사진.png
  iOS/moti/moti/Design/Sources/Design/MotiImage.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#123 카테고리 추가 버튼을 구현한다
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/프로필사진 1.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/프로필사진 2.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/DefaultProfile.imageset/프로필사진.png
  iOS/moti/moti/Design/Sources/Design/MotiImage.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#128 촬영 버튼을 재사용할 수 있도록 객체 분리한다.
  iOS/moti/moti/Design/Sources/Design/CaptureButton.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarViewController.swift
Labels: enhancement, iOS, 서포트

#130 네트워크 요청을 위해 Provider 수정, API 요청 확인
  iOS/moti/moti/Core/Sources/Core/Logger.swift
  iOS/moti/moti/Data/Sources/Data/Network/Common/NetworkError.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/AchievementDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/LoginResponseDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/ResponseDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/VersionDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/Endpoint.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/Requestable.swift
  iOS/moti/moti/Data/Sources/Data/Network/Provider/Provider.swift
  iOS/moti/moti/Data/Sources/Repository/LoginRepository.swift
  iOS/moti/moti/Data/Sources/Repository/Mock/MockRecordListRepository.swift
  iOS/moti/moti/Data/Sources/Repository/VersionRepository.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchCoodinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Login/LoginCoordinator.swift
Labels: feature, iOS, 메인

#133 어드민 등록 요청 및 로그인 API 작성하기
  BE/package-lock.json
  BE/package.json
  BE/src/admin/admin.module.ts
  BE/src/admin/application/admin.service.spec.ts
  BE/src/admin/application/admin.service.ts
  BE/src/admin/application/bcrypt-password-encoder.ts
  BE/src/admin/application/password-encoder.spec.ts
  BE/src/admin/application/password-encoder.ts
  BE/src/admin/application/plain-text-password-encoder.ts
  BE/src/admin/controller/admin-rest.controller.ts
  BE/src/admin/domain/admin-status.ts
  BE/src/admin/domain/admin.domain.ts
  BE/src/admin/dto/admin-login.ts
  BE/src/admin/dto/admin-register.ts
  BE/src/admin/dto/admin-token.ts
  BE/src/admin/entities/admin.entity.ts
  BE/src/admin/entities/admin.repository.spec.ts
  BE/src/admin/entities/admin.repository.ts
  BE/src/admin/exception/admin-invalid-password.ts
  BE/src/admin/exception/user-already-registered-admin.ts
  BE/src/app.module.ts
  BE/src/common/exception/error-code.ts
  BE/src/config/config/validation-decorator.ts
Labels: enhancement, BE, 서포트

#131 촬영 화면 Preview 구현
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
  iOS/moti/moti/Resource/Info.plist
Labels: feature, iOS, 메인

#136 Jeongfisher 제거, 로컬 이미지 표시
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Sample/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Sample/Sample1.imageset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Sample/Sample1.imageset/IMG_8195 1.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Sample/Sample1.imageset/IMG_8195 2.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Sample/Sample1.imageset/IMG_8195.png
  iOS/moti/moti/Design/Sources/Design/MotiImage.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/AchievementCollectionViewCell.swift
Labels: enhancement, iOS, 메인

#142 README 업데이트
  README.md
Labels: enhancement, 메인

#146 JWT 빌드할 때 payload에 권한 정보 삽입
  BE/src/admin/admin.module.ts
  BE/src/admin/application/admin.service.spec.ts
  BE/src/admin/application/admin.service.ts
  BE/src/admin/controller/admin-rest.controller.ts
  BE/src/admin/domain/admin.domain.spec.ts
  BE/src/admin/domain/admin.domain.ts
  BE/src/admin/entities/admin.entity.ts
  BE/src/admin/entities/admin.repository.ts
  BE/src/admin/exception/admin-invalid-password.exception.ts
  BE/src/admin/exception/user-already-registered-admin.exception.ts
  BE/src/admin/exception/user-not-admin-pending-status.exception.ts
  BE/src/auth/application/auth.service.ts
  BE/src/auth/guard/access-token.guard.ts
  BE/src/auth/guard/admin-token-guard.spec.ts
  BE/src/auth/guard/admin-token.guard.ts
  BE/src/auth/index.ts
  BE/src/common/exception/error-code.ts
  BE/src/common/filter/unexpected-exception.filter.ts
  BE/src/users/application/users.service.spec.ts
  BE/src/users/application/users.service.ts
  BE/src/users/domain/user-role.ts
  BE/src/users/domain/user.domain.ts
  BE/src/users/entities/role.entity.ts
  BE/src/users/entities/user.entity.ts
  BE/src/users/entities/user.repository.spec.ts
  BE/src/users/entities/user.repository.ts
  BE/src/users/entities/users-role.entity.ts
  BE/src/users/entities/users-role.repository.spec.ts
  BE/src/users/entities/users-role.repository.ts
  BE/test/admin/admin-fixture.ts
  BE/test/admin/admin-test.module.ts
  BE/test/user/users-test.module.ts
Labels: enhancement, BE, 서포트

#145 홈 화면 UI 여백 수정
  iOS/moti/moti/Presentation/Sources/Presentation/AutoLayout/AutoLayoutWrapper+UIView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/HeaderView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
Labels: enhancement, iOS, 메인

#161 [iOS] feat: LaunchVM에 Action, State 적용
  iOS/moti/moti/Application/AppCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewModel.swift
Labels: feature, iOS, 메인

#159 달성 기록 리스트 API를 작성한다.
  BE/src/achievement/achievement.module.ts
  BE/src/achievement/application/achievement.service.spec.ts
  BE/src/achievement/application/achievement.service.ts
  BE/src/achievement/controller/achievement.controller.ts
  BE/src/achievement/domain/achievement.domain.ts
  BE/src/achievement/dto/achievement-detail-response.ts
  BE/src/achievement/dto/achievement-response.ts
  BE/src/achievement/dto/paginate-achievement-request.ts
  BE/src/achievement/dto/paginate-achievement-response.spec.ts
  BE/src/achievement/dto/paginate-achievement-response.ts
  BE/src/achievement/entities/achievement.entity.ts
  BE/src/achievement/entities/achievement.repository.spec.ts
  BE/src/achievement/entities/achievement.repository.ts
  BE/src/achievement/index.ts
  BE/src/app.module.ts
  BE/src/config/validation/index.ts
  BE/test/achievement/achievement-fixture.ts
  BE/test/achievement/achievement-test.module.ts
  BE/test/category/category-fixture.ts
  BE/test/category/category-test.module.ts
Labels: BE, feature, 메인

#167 TextField를 포함한 Alert을 띄운다.
  iOS/moti/moti/Presentation/Sources/Presentation/Common/AlertFactory.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
Labels: feature, iOS, 메인

#168 HomeViewModel에 Action과 State를 적용한다
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: enhancement, iOS

#175 촬영 후 편집 UI 구현
  iOS/moti/moti/Application/AppCoordinator.swift
  iOS/moti/moti/Design/Sources/Design/UIFont+Extension.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/AchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/TextViewBottomSheet.swift
Labels: feature, iOS, 메인

#180 앨범에서 업로드할 사진 선택을 선택한다.
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Extension/UIImage+Extension.swift
Labels: feature, iOS, 메인

#181 전면, 후면 카메라 전환
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
Labels: feature, iOS, 메인

#179 사용자 본인에 대한 카테고리 리스트를 반환하는 API 작성하기
  BE/src/achievement/entities/achievement.entity.ts
  BE/src/category/application/category.service.spec.ts
  BE/src/category/application/category.service.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/category-list.response.spec.ts
  BE/src/category/dto/category-list.response.ts
  BE/src/category/dto/category-metadata.ts
  BE/src/category/entities/category.entity.ts
  BE/src/category/entities/category.repository.spec.ts
  BE/src/category/entities/category.repository.ts
  BE/src/category/index.ts
  BE/test/achievement/achievement-fixture.ts
  BE/test/category/category-fixture.ts
Labels: BE, feature, 메인

#182 선택한 카테고리의 달성 기록 리스트 API를 호출하고 표시한다.
  iOS/moti/moti.xcodeproj/project.pbxproj
  iOS/moti/moti/Data/.swiftpm/xcode/xcshareddata/xcschemes/DataTests.xcscheme
  iOS/moti/moti/Data/Sources/Data/Network/DTO/AchievementDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/AchievementListDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Repository/AchievementListRepository.swift
  iOS/moti/moti/Data/Sources/Repository/Mock/MockRecordListRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/AchievementListRepositoryTests.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockAchievementListRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockLoginRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockVersionRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/NetworkLoginRepositoryTests.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/Achievement.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/AchievementListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchAchievementListUseCase.swift
  iOS/moti/moti/Presentation/Package.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/AchievementCollectionViewCell.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#188 인증된 사용자에 대한 카테고리 목록 조회 API 포맷 변경
  BE/src/category/category.module.ts
  BE/src/category/controller/category-legacy.controller.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/category-list-element.response.ts
  BE/src/category/dto/category-list-legacy.response.ts
  BE/src/category/dto/category-list-regacy.response.spec.ts
Labels: enhancement, BE, 서포트

#189 카테고리 리스트 API를 요청한다
  iOS/moti/moti/Data/Package.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/AchievementListDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/CategoryListDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Repository/CategoryListRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/CategoryListRepositoryTests.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockAchievementListRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockCategoryListRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockLoginRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockVersionRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/NetworkLoginRepositoryTests.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/Achievement.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/CategoryItem.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/CategoryListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchCategoryListUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/CategoryCollectionViewCell.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/HeaderView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#195 달성 기록 (상세 정보) 화면 UI를 구현한다
  iOS/moti/moti/Presentation/Sources/Presentation/Detail/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Detail/DetailAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Detail/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#194 달성기록 상세조회 API를 구현한다.
  BE/src/achievement/application/achievement.service.spec.ts
  BE/src/achievement/application/achievement.service.ts
  BE/src/achievement/controller/achievement.controller.ts
  BE/src/achievement/dto/achievement-detail-response.ts
  BE/src/achievement/dto/category-info.ts
  BE/src/achievement/entities/achievement.repository.spec.ts
  BE/src/achievement/entities/achievement.repository.ts
  BE/src/achievement/exception/no-such-achievement.exception.ts
  BE/src/achievement/index.ts
  BE/src/common/exception/error-code.ts
Labels: BE, feature, 메인

#199 카테고리 저장 API 포맷 변경
  BE/src/achievement/dto/achievement-detail-response.ts
  BE/src/auth/decorator/athenticated-user.decorator.ts
  BE/src/category/dto/category-list-element.response.ts
  BE/src/category/dto/category-list-legacy.response.ts
  BE/src/category/dto/category-list-regacy.response.spec.ts
  BE/src/category/dto/category-metadata.ts
  BE/src/category/dto/category.response.ts
  BE/src/common/utils/date-formatter.spec.ts
  BE/src/common/utils/date-formatter.ts
Labels: enhancement, BE

#197 카테고리 추가 구현
  iOS/moti/moti/Data/Sources/Data/Network/DTO/CategoryListDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Data/Network/Provider/Provider.swift
  iOS/moti/moti/Data/Sources/Repository/CategoryListRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/CategoryListRepositoryTests.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockCategoryListRepository.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/CategoryItem.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/CategoryListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/AddCategoryUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/AlertFactory.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#202 서버리스 관련 세팅 및 다운 샘플링 스크립트를 작성한다.
  BE/scripts/down-sampling/.gitignore
  BE/scripts/down-sampling/__main__.py
  BE/scripts/down-sampling/requirements.txt
Labels: enhancement, BE

#204 다음 페이지네이션에 필요한 query param 응답 관련 버그
  BE/src/achievement/dto/paginate-achievement-response.spec.ts
  BE/src/achievement/dto/paginate-achievement-response.ts
Labels: BE, bug

#205 선택한 카테고리의 달성기록 리스트를 요청한다, 스크롤을 내리면 다음 페이지를 요청한다.
  iOS/moti/moti/Data/Sources/Data/Network/Provider/Provider.swift
  iOS/moti/moti/Data/Sources/Repository/AchievementListRepository.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/AchievementListRepositoryTests.swift
  iOS/moti/moti/Data/Tests/DataTests/Repository/Mock/MockAchievementListRepository.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/AchievementListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchAchievementListUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: feature, iOS, 메인

#209 EditAchievementViewController 분리 구현
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Detail/DetailAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Detail/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewController.swift
Labels: feature, iOS, 메인

#212 Achievement를 주입받아 EditAchievementViewController 생성
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/TextViewBottomSheet.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewModel.swift
Labels: feature, iOS, 메인

#213 달성기록 상세정보 API를 호출한다.
  iOS/moti/moti/Application/AppCoordinator.swift
  iOS/moti/moti/Data/Sources/Data/Network/DTO/DetailAchievementDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Repository/DetailAchievementRepository.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/Achievement.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/DetailAchievementRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchDetailAchievementUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Detail/DetailAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Detail/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
Labels: feature, iOS, 메인

#218 CI 스크립트 수정
  .github/workflows/be.ci.yml
Labels: BE, 서포트

#220 릴리즈 전 종합적인 버그 수정
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: enhancement, iOS, bug

#222 최초 로그인 때 스플래시만 뜨는 버그 수정
  iOS/moti/moti/Presentation/Sources/Presentation/Launch/LaunchViewModel.swift
Labels: iOS, 메인, bug

#226 커스텀 ParseIntPipe 만들기
  BE/src/achievement/controller/achievement.controller.ts
  BE/src/common/pipe/parse-int.pipe.spec.ts
  BE/src/common/pipe/parse-int.pipe.ts
Labels: enhancement, BE, 서포트

#208 로컬에 사진을 저장할 수 있다.
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/application/file-store/fail-file-task.exception.ts
  BE/src/common/application/file-store/file-store.module.ts
  BE/src/common/application/file-store/file-store.ts
  BE/src/common/application/file-store/index.ts
  BE/src/common/application/file-store/local-file-store.spec.ts
  BE/src/common/application/file-store/local-file-store.ts
  BE/src/common/application/uuid-holder/default-uuid-holder.ts
  BE/src/common/application/uuid-holder/index.ts
  BE/src/common/application/uuid-holder/uuid-holder.ts
  BE/src/common/application/uuid-holder/uuid.module.ts
  BE/src/common/exception/error-code.ts
  BE/src/config/config/index.ts
  BE/test/common/file-store/file-fixture.ts
  BE/test/common/uuid-holder/stub-uuid-holder.ts
Labels: BE, feature, 메인

#248 [iOS] feat: bottom sheet에 완료 버튼 추가
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/TextViewBottomSheet.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewController.swift
Labels: feature, iOS, 서포트

#249 swagger 옵션 추가 및 보완하기
  BE/src/achievement/controller/achievement.controller.ts
  BE/src/achievement/dto/paginate-achievement-request.ts
  BE/src/admin/controller/admin-rest.controller.ts
  BE/src/admin/dto/admin-login.ts
  BE/src/admin/dto/admin-register.ts
  BE/src/auth/controller/auth.controller.ts
  BE/src/category/controller/category-legacy.controller.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/category-list-element.response.ts
  BE/src/category/dto/category-list-legacy.response.ts
  BE/src/config/swagger/index.ts
  BE/src/operate/controller/operate-mvc.controller.ts
  BE/src/operate/controller/operate.controller.ts
Labels: enhancement, BE, 서포트

#219 S3에 사진을 저장할 수 있다.
  .github/workflows/be.ci.yml
  BE/package-lock.json
  BE/package.json
  BE/src/common/application/file-store/file-store-provider-options.ts
  BE/src/common/application/file-store/file-store.module.ts
  BE/src/common/application/file-store/file-store.ts
  BE/src/common/application/file-store/local-file-store.spec.ts
  BE/src/common/application/file-store/local-file-store.ts
  BE/src/common/application/file-store/object-storage-file-store.spec.ts
  BE/src/common/application/file-store/object-storage-file-store.ts
  BE/test/common/ci-skip-test.ts
Labels: BE, 메인

#257 사진 선저장 API 작성하기
  .github/workflows/be.cd.yml
  .github/workflows/be.ci.yml
  BE/.gitignore
  BE/package-lock.json
  BE/package.json
  BE/scripts/multipart-sender/.gitignore
  BE/scripts/multipart-sender/__main__.py
  BE/src/app.module.ts
  BE/src/common/application/file-store/file-store.module.ts
  BE/src/common/application/file-store/local-file-store.spec.ts
  BE/src/common/application/file-store/local-file-store.ts
  BE/src/common/application/file-store/object-storage-file-store.spec.ts
  BE/src/common/application/file-store/object-storage-file-store.ts
  BE/src/common/pipe/parse-file.pipe.ts
  BE/src/config/config/index.ts
  BE/src/config/typeorm/index.ts
  BE/src/image/application/image.service.spec.ts
  BE/src/image/application/image.service.ts
  BE/src/image/controller/image.controller.spec.ts
  BE/src/image/controller/image.controller.ts
  BE/src/image/domain/image.domain.spec.ts
  BE/src/image/domain/image.domain.ts
  BE/src/image/dto/image-response.ts
  BE/src/image/entities/image.entity.spec.ts
  BE/src/image/entities/image.entity.ts
  BE/src/image/entities/image.repository.spec.ts
  BE/src/image/entities/image.repository.ts
  BE/src/image/image.module.ts
  BE/test/auth/auth-fixture.ts
  BE/test/auth/auth-test.module.ts
  BE/test/auth/index.ts
  BE/test/image/image.e2e-spec.ts
  BE/test/resources/error.png
  BE/test/resources/img.png
Labels: BE, 메인

#293 달성 기록 (상세 정보) 화면 UI를 구현한다2
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementView.swift
Labels: feature, iOS, 메인

#291 썸네일 저장 API 작성하기
  BE/src/auth/guard/admin-token.guard.ts
  BE/src/common/exception/error-code.ts
  BE/src/image/application/image.service.spec.ts
  BE/src/image/application/image.service.ts
  BE/src/image/controller/image.controller.spec.ts
  BE/src/image/controller/image.controller.ts
  BE/src/image/domain/image.domain.ts
  BE/src/image/dto/thumbnail-request.ts
  BE/src/image/entities/image.repository.spec.ts
  BE/src/image/entities/image.repository.ts
  BE/src/image/exception/image-already-exists-thumbnail.exception.ts
  BE/src/image/exception/image-not-found.exception.ts
  BE/test/auth/auth-fixture.ts
  BE/test/auth/auth-test.module.ts
  BE/test/auth/index.ts
  BE/test/image/image-fixture.ts
  BE/test/image/image-test.module.ts
  BE/test/image/image.e2e-spec.ts
Labels: BE, feature, 메인

#295 카테고리, 제목, 내용의 편집 모드로 변한다.
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewModel.swift
Labels: feature, iOS, 메인

#296 그룹 테이블을 설계한다.
  BE/src/group/achievement/domain/group-achievement.domain.ts
  BE/src/group/achievement/domain/user-blocked-group-achievement.domain.ts
  BE/src/group/achievement/entities/group-achievement.entity.spec.ts
  BE/src/group/achievement/entities/group-achievement.entity.ts
  BE/src/group/achievement/entities/user-blocked-group-achievement.entity.spec.ts
  BE/src/group/achievement/entities/user-blocked-group-achievement.entity.ts
  BE/src/group/category/domain/group.category.ts
  BE/src/group/category/entities/group-category.entity.spec.ts
  BE/src/group/category/entities/group-category.entity.ts
  BE/src/group/group/domain/group.domain.ts
  BE/src/group/group/domain/user-group-grade.ts
  BE/src/group/group/domain/user-group.doamin.ts
  BE/src/group/group/entities/group.entity.ts
  BE/src/group/group/entities/user-group.entity.spec.ts
  BE/src/group/group/entities/user-group.entity.ts
  BE/src/group/image/domain/group-achievement-image.domain.ts
  BE/src/group/image/entities/group-achievement-image.entity.ts
  BE/src/group/image/entities/group-ahievement-image.entity.spec.ts
  BE/src/users/domain/user-blocked-user.domain.ts
  BE/src/users/entities/user-blocked-user.entity.spec.ts
  BE/src/users/entities/user-blocked-user.entity.ts
  BE/test/group/achievement/group-achievement-fixture.ts
  BE/test/group/category/group-category-fixture.ts
  BE/test/group/group/group-fixture.ts
Labels: BE, feature, 메인

#298 달성기록 삭제 수정 API를 추가한다.
  BE/src/achievement/achievement.module.ts
  BE/src/achievement/application/achievement.service.spec.ts
  BE/src/achievement/application/achievement.service.ts
  BE/src/achievement/controller/achievement.controller.ts
  BE/src/achievement/domain/achievement.domain.ts
  BE/src/achievement/dto/achievement-delete-response.ts
  BE/src/achievement/dto/achievement-update-request.ts
  BE/src/achievement/dto/achievement-update-response.ts
  BE/src/achievement/entities/achievement.repository.spec.ts
  BE/src/achievement/entities/achievement.repository.ts
  BE/src/achievement/exception/invalid-category.exception.ts
  BE/src/achievement/index.ts
  BE/src/category/entities/category.repository.spec.ts
  BE/src/category/entities/category.repository.ts
  BE/src/common/exception/error-code.ts
Labels: BE, feature, 메인

#300 삭제 버튼을 누르면 삭제를 할 것인지 확인하는 Alert을 띄운다.
  iOS/moti/moti/Presentation/Sources/Presentation/Common/AlertFactory.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/BaseViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
Labels: feature, iOS, 메인

#303 삭제 버튼이 눌리면 홈 화면으로 이동하고, 데이터를 업데이트한다.
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: feature, iOS, 메인

#305 달성기록 조회 페이징 디폴트 개수 변경
  BE/src/achievement/dto/paginate-achievement-request.ts
  BE/src/achievement/entities/achievement.repository.spec.ts
Labels: enhancement, BE

#306 Alert의 OK를 누르면 삭제 API를 호출한다.
  iOS/moti/moti/Data/Sources/Data/Network/DTO/DeleteAchievementDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Repository/DeleteAchievementRepository.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/DeleteAchievementRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/DeleteAchievementUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewModel.swift
Labels: feature, iOS, 메인

#309 달성 기록 저장 API 작성하기
  BE/src/achievement/achievement.module.ts
  BE/src/achievement/application/achievement.service.spec.ts
  BE/src/achievement/application/achievement.service.ts
  BE/src/achievement/controller/achievement.controller.spec.ts
  BE/src/achievement/controller/achievement.controller.ts
  BE/src/achievement/domain/achievement.domain.ts
  BE/src/achievement/dto/achievement-create-request.ts
  BE/src/achievement/dto/achievement-response.ts
  BE/src/achievement/dto/achievement-update-request.ts
  BE/src/achievement/entities/achievement.entity.spec.ts
  BE/src/achievement/entities/achievement.entity.ts
  BE/src/achievement/entities/achievement.repository.spec.ts
  BE/src/achievement/entities/achievement.repository.ts
  BE/src/achievement/exception/no-user-image-exception.ts
  BE/src/category/entities/category.entity.ts
  BE/src/category/entities/category.repository.spec.ts
  BE/src/category/entities/category.repository.ts
  BE/src/common/exception/error-code.ts
  BE/src/config/config/index.ts
  BE/src/config/transaction-manager/transactional-repository.ts
  BE/src/config/typeorm/index.ts
  BE/src/image/entities/image.entity.spec.ts
  BE/src/image/entities/image.entity.ts
  BE/src/image/entities/image.repository.ts
  BE/test/achievement/achievement-fixture.ts
  BE/test/achievement/achievement-test.module.ts
  BE/test/auth/auth-fixture.ts
  BE/test/image/image-fixture.ts
Labels: enhancement, BE, feature, 메인

#313 스켈레톤 이미지 구현
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/Skeleton.imageset/Contents.json
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/Skeleton.imageset/skeleton 1.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/Skeleton.imageset/skeleton 2.png
  iOS/moti/moti/Design/Sources/Design/Design.xcassets/Logo/Skeleton.imageset/skeleton.png
  iOS/moti/moti/Design/Sources/Design/MotiImage.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/Cell/AchievementCollectionViewCell.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: feature, iOS

#316 달성 기록 저장 API 작성하기
  BE/src/achievement/application/achievement.service.spec.ts
  BE/src/achievement/application/achievement.service.ts
  BE/src/achievement/dto/achievement-response.spec.ts
  BE/src/achievement/dto/achievement-response.ts
  BE/src/achievement/entities/achievement.entity.spec.ts
  BE/src/achievement/entities/achievement.entity.ts
  BE/src/admin/entities/admin.entity.ts
  BE/src/category/entities/category.entity.ts
  BE/src/common/utils/is-null-or-undefined.ts
  BE/src/config/transaction-manager/transactional-repository.ts
  BE/src/image/entities/image.entity.spec.ts
  BE/src/image/entities/image.entity.ts
  BE/src/image/entities/image.repository.ts
  BE/src/users/entities/user-blocked-user.entity.spec.ts
  BE/src/users/entities/user-blocked-user.entity.ts
  BE/src/users/entities/user.entity.ts
  BE/test/achievement/achievement-fixture.ts
  BE/test/common/file-store/file-fixture.ts
  BE/test/common/transaction-test.ts
Labels: BE, feature, 메인

#319 편집을 완료하면 카테고리, 제목, 내용의 읽기 모드로 변한다.
  iOS/moti/moti/Domain/Sources/Domain/Entity/Achievement.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/UpdateAchievementUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#321 CategoryStorage 구현
  iOS/moti/moti/Data/Sources/Repository/CategoryListRepository.swift
  iOS/moti/moti/Data/Sources/Storage/CategoryStorage.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/CategoryItem.swift
  iOS/moti/moti/Domain/Sources/Domain/StorageProtocol/CategoryStorageProtocol.swift
Labels: enhancement, feature, 메인

#320 썸네일 저장 API 수정
  BE/src/common/application/file-store/file-store.ts
  BE/src/common/application/file-store/index.ts
  BE/src/common/application/file-store/local-file-store.ts
  BE/src/common/application/file-store/object-storage-file-store.ts
  BE/src/common/pipe/parse-not-empty.pipe.ts
  BE/src/image/application/image.service.spec.ts
  BE/src/image/application/image.service.ts
  BE/src/image/controller/image.controller.ts
  BE/src/image/domain/image.domain.ts
  BE/src/image/entities/image.entity.ts
  BE/src/image/entities/image.repository.spec.ts
  BE/src/image/entities/image.repository.ts
  BE/test/image/image-fixture.ts
Labels: enhancement, BE, 서포트

#325 AchievementRepository 통합
  iOS/moti/moti/Data/Sources/Repository/AchievementListRepository.swift
  iOS/moti/moti/Data/Sources/Repository/AchievementRepository.swift
  iOS/moti/moti/Data/Sources/Repository/DeleteAchievementRepository.swift
  iOS/moti/moti/Data/Sources/Repository/DetailAchievementRepository.swift
  iOS/moti/moti/Data/Sources/Repository/UpdateAchievementRepository.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/AchievementListRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/AchievementRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/DeleteAchievementUseCase.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchAchievementListUseCase.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/FetchDetailAchievementUseCase.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/UpdateAchievementUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: enhancement, iOS

#327 탭바 보이기/숨기기 구현, 상세->편집화면 present로 변경
  iOS/moti/moti/Application/Base.lproj/LaunchScreen.storyboard
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarViewController.swift
Labels: enhancement, iOS, 메인

#328 레포지토리 테스트 보완
  BE/src/achievement/entities/achievement.repository.spec.ts
  BE/src/image/entities/image.repository.spec.ts
Labels: enhancement, BE

#331 그룹리스트 화면 UI 구현
  iOS/moti/moti/Design/Sources/Design/UIFont+Extension.swift
  iOS/moti/moti/Domain/Sources/Domain/Entity/GroupListItem.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Common/CompositionalLayoutFactory.swift
  iOS/moti/moti/Presentation/Sources/Presentation/GroupList/Cell/GroupListCollectionViewCell.swift
  iOS/moti/moti/Presentation/Sources/Presentation/GroupList/GroupListCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/GroupList/GroupListView.swift
  iOS/moti/moti/Presentation/Sources/Presentation/GroupList/GroupListViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/GroupList/GroupListViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#334 TabBarCoordinator 흐름 정리
  iOS/moti/moti/Presentation/Sources/Presentation/GroupList/GroupListCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: enhancement, iOS, 메인

#332 그룹 리스트 API 구현
  BE/src/group/achievement/domain/group-achievement.domain.ts
  BE/src/group/achievement/entities/group-achievement.entity.ts
  BE/src/group/achievement/entities/group-achievement.repository.ts
  BE/src/group/category/entities/group-category.repository.ts
  BE/src/group/group/application/group.service.spec.ts
  BE/src/group/group/application/group.service.ts
  BE/src/group/group/controller/group.controller.spec.ts
  BE/src/group/group/controller/group.controller.ts
  BE/src/group/group/dto/group-list-response.ts
  BE/src/group/group/dto/group-preview.dto.ts
  BE/src/group/group/entities/group.repository.spec.ts
  BE/src/group/group/entities/group.repository.ts
  BE/src/group/group/index.ts
  BE/test/group/achievement/group-achievement-fixture.ts
  BE/test/group/achievement/group-achievement-test.module.ts
  BE/test/group/category/group-category-fixture.ts
  BE/test/group/category/group-category-test.module.ts
  BE/test/group/group/group-fixture.ts
  BE/test/group/group/group-test.module.ts
Labels: BE, feature, 메인

#341 그룹 기본 로고 설정로직을 추가한다.
  .github/workflows/be.cd.yml
  .github/workflows/be.ci.yml
  BE/src/group/group/application/group-avatar.holder.spec.ts
  BE/src/group/group/application/group-avatar.holder.ts
  BE/src/group/group/application/group.service.spec.ts
  BE/src/group/group/application/group.service.ts
  BE/src/group/group/domain/group.domain.spec.ts
  BE/src/group/group/domain/group.domain.ts
  BE/src/group/group/dto/create-group-request.dto.ts
  BE/src/group/group/group.module.ts
Labels: BE, feature

#346 달성기록 편집 시 홈 화면의 헤더뷰를 업데이트한다. / HomeViewModel 가독성 개선
  iOS/moti/moti/Data/Sources/Storage/CategoryStorage.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeActionState.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: feature, iOS, 메인

#342 그룹의 카테고리를 생성하는 API 작성한다.
  BE/src/app.module.ts
  BE/src/common/exception/error-code.ts
  BE/src/config/config/index.ts
  BE/src/config/config/validation-decorator.ts
  BE/src/group/category/application/group-category.service.spec.ts
  BE/src/group/category/application/group-category.service.ts
  BE/src/group/category/controller/group-category.controller.spec.ts
  BE/src/group/category/controller/group-category.controller.ts
  BE/src/group/category/dto/group-category-create.ts
  BE/src/group/category/dto/group-category-response.ts
  BE/src/group/category/entities/group-category.repository.spec.ts
  BE/src/group/category/entities/group-category.repository.ts
  BE/src/group/category/exception/unauthorized-group-category.exception.ts
  BE/src/group/category/group-category.module.ts
  BE/src/group/group/entities/group.repository.spec.ts
  BE/src/group/group/entities/group.repository.ts
  BE/test/group/group/group-fixture.ts
  BE/test/group/group/group-test.module.ts
  BE/test/user/users-fixture.ts
Labels: BE, feature, 메인

#349 달성 기록 등록 API 응답이 OK면 홈 화면으로 이동한다.
  iOS/moti/moti/Data/Sources/Data/Network/DTO/AchievementListDTO.swift
  iOS/moti/moti/Data/Sources/Data/Network/Endpoint/MotiAPI.swift
  iOS/moti/moti/Data/Sources/Repository/AchievementRepository.swift
  iOS/moti/moti/Domain/Sources/Domain/RepositoryProtocol/AchievementRepositoryProtocol.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/PostAchievementUseCase.swift
  iOS/moti/moti/Domain/Sources/Domain/UseCase/SaveImageUseCase.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Capture/CaptureCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/DetailAchievement/DetailAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/EditAchievement/EditAchievementViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeActionState.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeCoordinator.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewController.swift
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
  iOS/moti/moti/Presentation/Sources/Presentation/TabBar/TabBarCoordinator.swift
Labels: feature, iOS, 메인

#352 currentCategory가 전체 카테고리일 때 헤더뷰 업데이트 버그 수정
  iOS/moti/moti/Presentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: iOS, 메인, bug
